// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Biome string

const (
	BiomeAmazonia      Biome = "amazonia"
	BiomeMataAtlantica Biome = "mata_atlantica"
	BiomeCerrado       Biome = "cerrado"
	BiomeCaatinga      Biome = "caatinga"
	BiomePantanal      Biome = "pantanal"
	BiomePampa         Biome = "pampa"
)

func (e *Biome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Biome(s)
	case string:
		*e = Biome(s)
	default:
		return fmt.Errorf("unsupported scan type for Biome: %T", src)
	}
	return nil
}

type NullBiome struct {
	Biome Biome
	Valid bool // Valid is true if Biome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBiome) Scan(value interface{}) error {
	if value == nil {
		ns.Biome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Biome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBiome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Biome), nil
}

type IngestionJob struct {
	ID        int64
	SpeciesID string
	Source    string
	Status    string
	Attempts  int32
	NextRunAt pgtype.Timestamptz
	LastError string
	UpdatedAt pgtype.Timestamptz
}

type Medium struct {
	ID         int64
	SpeciesID  string
	Kind       string
	Position   int32
	ThumbKey   string
	MediumKey  string
	LargeKey   string
	AudioKey   string
	Width      int32
	Height     int32
	DurationMs int32
	Author     string
	License    string
	Source     string
	SourceUrl  string
	CreatedAt  pgtype.Timestamptz
}

type OccurrenceCluster struct {
	SpeciesID string
	Lat       float64
	Lng       float64
	Count     int32
	Precision float64
}

type Species struct {
	ID                   string
	ScientificName       string
	CommonNamePt         string
	Family               string
	SizeCm               pgtype.Int4
	Diet                 pgtype.Text
	ConservationStatus   string
	Description          string
	DescriptionAuthor    string
	DescriptionLicense   string
	DescriptionSource    string
	DescriptionSourceUrl string
	IsCurated            bool
	SortName             string
	SearchText           string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type SpeciesBiome struct {
	SpeciesID string
	Biome     Biome
}

type SpeciesFact struct {
	ID        int64
	SpeciesID string
	Position  int32
	Text      string
	Source    string
}

type SpeciesState struct {
	SpeciesID string
	Uf        string
}
