// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countByBiome = `-- name: CountByBiome :many
SELECT biome, count(*)::int AS total FROM species_biome GROUP BY biome
`

type CountByBiomeRow struct {
	Biome Biome
	Total int32
}

func (q *Queries) CountByBiome(ctx context.Context) ([]CountByBiomeRow, error) {
	rows, err := q.db.Query(ctx, countByBiome)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountByBiomeRow
	for rows.Next() {
		var i CountByBiomeRow
		if err := rows.Scan(&i.Biome, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countByState = `-- name: CountByState :many
SELECT uf::text AS uf, count(*)::int AS total FROM species_state GROUP BY uf
`

type CountByStateRow struct {
	Uf    string
	Total int32
}

func (q *Queries) CountByState(ctx context.Context) ([]CountByStateRow, error) {
	rows, err := q.db.Query(ctx, countByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountByStateRow
	for rows.Next() {
		var i CountByStateRow
		if err := rows.Scan(&i.Uf, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBiomes = `-- name: DeleteBiomes :exec
DELETE FROM species_biome WHERE species_id = $1
`

func (q *Queries) DeleteBiomes(ctx context.Context, speciesID string) error {
	_, err := q.db.Exec(ctx, deleteBiomes, speciesID)
	return err
}

const deleteFacts = `-- name: DeleteFacts :exec
DELETE FROM species_fact WHERE species_id = $1
`

func (q *Queries) DeleteFacts(ctx context.Context, speciesID string) error {
	_, err := q.db.Exec(ctx, deleteFacts, speciesID)
	return err
}

const deleteStates = `-- name: DeleteStates :exec
DELETE FROM species_state WHERE species_id = $1
`

func (q *Queries) DeleteStates(ctx context.Context, speciesID string) error {
	_, err := q.db.Exec(ctx, deleteStates, speciesID)
	return err
}

const getSpecies = `-- name: GetSpecies :one
SELECT id, scientific_name, common_name_pt, family, size_cm, diet, conservation_status, description, description_author, description_license, description_source, description_source_url, is_curated, sort_name, search_text, created_at, updated_at FROM species WHERE id = $1
`

func (q *Queries) GetSpecies(ctx context.Context, id string) (Species, error) {
	row := q.db.QueryRow(ctx, getSpecies, id)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.ScientificName,
		&i.CommonNamePt,
		&i.Family,
		&i.SizeCm,
		&i.Diet,
		&i.ConservationStatus,
		&i.Description,
		&i.DescriptionAuthor,
		&i.DescriptionLicense,
		&i.DescriptionSource,
		&i.DescriptionSourceUrl,
		&i.IsCurated,
		&i.SortName,
		&i.SearchText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBiome = `-- name: InsertBiome :exec
INSERT INTO species_biome (species_id, biome) VALUES ($1, $2)
`

type InsertBiomeParams struct {
	SpeciesID string
	Biome     Biome
}

func (q *Queries) InsertBiome(ctx context.Context, arg InsertBiomeParams) error {
	_, err := q.db.Exec(ctx, insertBiome, arg.SpeciesID, arg.Biome)
	return err
}

const insertFact = `-- name: InsertFact :exec
INSERT INTO species_fact (species_id, position, text, source) VALUES ($1, $2, $3, $4)
`

type InsertFactParams struct {
	SpeciesID string
	Position  int32
	Text      string
	Source    string
}

func (q *Queries) InsertFact(ctx context.Context, arg InsertFactParams) error {
	_, err := q.db.Exec(ctx, insertFact,
		arg.SpeciesID,
		arg.Position,
		arg.Text,
		arg.Source,
	)
	return err
}

const insertState = `-- name: InsertState :exec
INSERT INTO species_state (species_id, uf) VALUES ($1, $2)
`

type InsertStateParams struct {
	SpeciesID string
	Uf        string
}

func (q *Queries) InsertState(ctx context.Context, arg InsertStateParams) error {
	_, err := q.db.Exec(ctx, insertState, arg.SpeciesID, arg.Uf)
	return err
}

const listBiomes = `-- name: ListBiomes :many
SELECT biome FROM species_biome WHERE species_id = $1 ORDER BY biome
`

func (q *Queries) ListBiomes(ctx context.Context, speciesID string) ([]Biome, error) {
	rows, err := q.db.Query(ctx, listBiomes, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Biome
	for rows.Next() {
		var biome Biome
		if err := rows.Scan(&biome); err != nil {
			return nil, err
		}
		items = append(items, biome)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusters = `-- name: ListClusters :many
SELECT lat, lng, count, precision FROM occurrence_cluster WHERE species_id = $1 ORDER BY count DESC
`

type ListClustersRow struct {
	Lat       float64
	Lng       float64
	Count     int32
	Precision float64
}

func (q *Queries) ListClusters(ctx context.Context, speciesID string) ([]ListClustersRow, error) {
	rows, err := q.db.Query(ctx, listClusters, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClustersRow
	for rows.Next() {
		var i ListClustersRow
		if err := rows.Scan(
			&i.Lat,
			&i.Lng,
			&i.Count,
			&i.Precision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacts = `-- name: ListFacts :many
SELECT text, source FROM species_fact WHERE species_id = $1 ORDER BY position
`

type ListFactsRow struct {
	Text   string
	Source string
}

func (q *Queries) ListFacts(ctx context.Context, speciesID string) ([]ListFactsRow, error) {
	rows, err := q.db.Query(ctx, listFacts, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactsRow
	for rows.Next() {
		var i ListFactsRow
		if err := rows.Scan(&i.Text, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedia = `-- name: ListMedia :many
SELECT id, species_id, kind, position, thumb_key, medium_key, large_key, audio_key, width, height, duration_ms, author, license, source, source_url, created_at FROM media WHERE species_id = $1 ORDER BY kind, position
`

func (q *Queries) ListMedia(ctx context.Context, speciesID string) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Kind,
			&i.Position,
			&i.ThumbKey,
			&i.MediumKey,
			&i.LargeKey,
			&i.AudioKey,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Author,
			&i.License,
			&i.Source,
			&i.SourceUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecies = `-- name: ListSpecies :many
SELECT s.id, s.scientific_name, s.common_name_pt, s.conservation_status,
       COALESCE((SELECT m.thumb_key FROM media m
                 WHERE m.species_id = s.id AND m.kind = 'photo'
                 ORDER BY m.position LIMIT 1), '')::text AS thumbnail_key
FROM species s
WHERE ($1::text IS NULL OR s.search_text LIKE '%' || $1::text || '%' ESCAPE '\')
  AND ($2::biome IS NULL OR EXISTS (
        SELECT 1 FROM species_biome b WHERE b.species_id = s.id AND b.biome = $2::biome))
  AND ($3::text IS NULL OR EXISTS (
        SELECT 1 FROM species_state st WHERE st.species_id = s.id AND st.uf = $3::text))
  AND ($4::text IS NULL
       OR (s.sort_name, s.id) > ($4::text, $5::text))
ORDER BY s.sort_name, s.id
LIMIT $6
`

type ListSpeciesParams struct {
	Query     pgtype.Text
	Biome     NullBiome
	State     pgtype.Text
	AfterSort pgtype.Text
	AfterID   pgtype.Text
	Lim       int32
}

type ListSpeciesRow struct {
	ID                 string
	ScientificName     string
	CommonNamePt       string
	ConservationStatus string
	ThumbnailKey       string
}

// Lista resumida com busca, filtros e paginação por cursor.
// Cada filtro é opcional: "(parâmetro IS NULL OR condição)".
func (q *Queries) ListSpecies(ctx context.Context, arg ListSpeciesParams) ([]ListSpeciesRow, error) {
	rows, err := q.db.Query(ctx, listSpecies,
		arg.Query,
		arg.Biome,
		arg.State,
		arg.AfterSort,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeciesRow
	for rows.Next() {
		var i ListSpeciesRow
		if err := rows.Scan(
			&i.ID,
			&i.ScientificName,
			&i.CommonNamePt,
			&i.ConservationStatus,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStates = `-- name: ListStates :many
SELECT uf::text FROM species_state WHERE species_id = $1 ORDER BY uf
`

func (q *Queries) ListStates(ctx context.Context, speciesID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listStates, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var uf string
		if err := rows.Scan(&uf); err != nil {
			return nil, err
		}
		items = append(items, uf)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSpecies = `-- name: UpsertSpecies :exec
INSERT INTO species (id, scientific_name, common_name_pt, family, size_cm, diet, conservation_status,
                     description, description_author, description_license, description_source,
                     description_source_url, is_curated, sort_name, search_text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, true, $13, $14)
ON CONFLICT (id) DO UPDATE SET
    scientific_name = EXCLUDED.scientific_name, common_name_pt = EXCLUDED.common_name_pt,
    family = EXCLUDED.family, size_cm = EXCLUDED.size_cm, diet = EXCLUDED.diet,
    conservation_status = EXCLUDED.conservation_status, description = EXCLUDED.description,
    description_author = EXCLUDED.description_author, description_license = EXCLUDED.description_license,
    description_source = EXCLUDED.description_source, description_source_url = EXCLUDED.description_source_url,
    is_curated = true, sort_name = EXCLUDED.sort_name, search_text = EXCLUDED.search_text,
    updated_at = now()
`

type UpsertSpeciesParams struct {
	ID                   string
	ScientificName       string
	CommonNamePt         string
	Family               string
	SizeCm               pgtype.Int4
	Diet                 pgtype.Text
	ConservationStatus   string
	Description          string
	DescriptionAuthor    string
	DescriptionLicense   string
	DescriptionSource    string
	DescriptionSourceUrl string
	SortName             string
	SearchText           string
}

// "Upsert" = insere, ou atualiza se o id já existir. Só mexe nos campos
// curados; created_at é preservado.
func (q *Queries) UpsertSpecies(ctx context.Context, arg UpsertSpeciesParams) error {
	_, err := q.db.Exec(ctx, upsertSpecies,
		arg.ID,
		arg.ScientificName,
		arg.CommonNamePt,
		arg.Family,
		arg.SizeCm,
		arg.Diet,
		arg.ConservationStatus,
		arg.Description,
		arg.DescriptionAuthor,
		arg.DescriptionLicense,
		arg.DescriptionSource,
		arg.DescriptionSourceUrl,
		arg.SortName,
		arg.SearchText,
	)
	return err
}
