// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_ingest.sql

package sqlcgen

import (
	"context"
)

const claimDueJobs = `-- name: ClaimDueJobs :many
UPDATE ingestion_job j SET status = 'running', updated_at = now()
FROM species s
WHERE j.species_id = s.id AND j.id IN (
    SELECT id FROM ingestion_job
    WHERE status = 'pending' AND next_run_at <= now()
    ORDER BY next_run_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED)
RETURNING j.id, j.species_id, s.scientific_name, j.source, j.attempts
`

type ClaimDueJobsRow struct {
	ID             int64
	SpeciesID      string
	ScientificName string
	Source         string
	Attempts       int32
}

// FOR UPDATE SKIP LOCKED: se outro worker já travou uma linha nesta
// transação, pulamos ela em vez de esperar. É o padrão clássico de
// "fila no PostgreSQL" sem dois workers pegarem o mesmo job.
func (q *Queries) ClaimDueJobs(ctx context.Context, lim int32) ([]ClaimDueJobsRow, error) {
	rows, err := q.db.Query(ctx, claimDueJobs, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueJobsRow
	for rows.Next() {
		var i ClaimDueJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.ScientificName,
			&i.Source,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeJob = `-- name: CompleteJob :exec
UPDATE ingestion_job SET status = 'done', last_error = '', updated_at = now() WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const countPendingJobs = `-- name: CountPendingJobs :one
SELECT count(*)::int FROM ingestion_job WHERE status = 'pending'
`

func (q *Queries) CountPendingJobs(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingJobs)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteClusters = `-- name: DeleteClusters :exec
DELETE FROM occurrence_cluster WHERE species_id = $1
`

func (q *Queries) DeleteClusters(ctx context.Context, speciesID string) error {
	_, err := q.db.Exec(ctx, deleteClusters, speciesID)
	return err
}

const deleteMediaByKind = `-- name: DeleteMediaByKind :exec
DELETE FROM media WHERE species_id = $1 AND kind = $2
`

type DeleteMediaByKindParams struct {
	SpeciesID string
	Kind      string
}

func (q *Queries) DeleteMediaByKind(ctx context.Context, arg DeleteMediaByKindParams) error {
	_, err := q.db.Exec(ctx, deleteMediaByKind, arg.SpeciesID, arg.Kind)
	return err
}

const enqueueMissingJobs = `-- name: EnqueueMissingJobs :exec
INSERT INTO ingestion_job (species_id, source)
SELECT s.id, src FROM species s CROSS JOIN unnest($1::text[]) AS src
ON CONFLICT (species_id, source) DO NOTHING
`

// Cria (espécie × fonte) que ainda não existe. ON CONFLICT DO NOTHING
// torna a operação idempotente.
func (q *Queries) EnqueueMissingJobs(ctx context.Context, sources []string) error {
	_, err := q.db.Exec(ctx, enqueueMissingJobs, sources)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE ingestion_job SET
    status = CASE WHEN $1::bool THEN 'failed' ELSE 'pending' END,
    attempts = attempts + 1,
    last_error = $2,
    next_run_at = now() + make_interval(secs => $3::double precision),
    updated_at = now()
WHERE id = $4
`

type FailJobParams struct {
	GiveUp      bool
	LastError   string
	RetryInSecs float64
	ID          int64
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob,
		arg.GiveUp,
		arg.LastError,
		arg.RetryInSecs,
		arg.ID,
	)
	return err
}

const insertCluster = `-- name: InsertCluster :exec
INSERT INTO occurrence_cluster (species_id, lat, lng, count, precision) VALUES ($1, $2, $3, $4, $5)
`

type InsertClusterParams struct {
	SpeciesID string
	Lat       float64
	Lng       float64
	Count     int32
	Precision float64
}

func (q *Queries) InsertCluster(ctx context.Context, arg InsertClusterParams) error {
	_, err := q.db.Exec(ctx, insertCluster,
		arg.SpeciesID,
		arg.Lat,
		arg.Lng,
		arg.Count,
		arg.Precision,
	)
	return err
}

const insertMedia = `-- name: InsertMedia :exec
INSERT INTO media (species_id, kind, position, thumb_key, medium_key, large_key, audio_key,
                   width, height, duration_ms, author, license, source, source_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertMediaParams struct {
	SpeciesID  string
	Kind       string
	Position   int32
	ThumbKey   string
	MediumKey  string
	LargeKey   string
	AudioKey   string
	Width      int32
	Height     int32
	DurationMs int32
	Author     string
	License    string
	Source     string
	SourceUrl  string
}

func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) error {
	_, err := q.db.Exec(ctx, insertMedia,
		arg.SpeciesID,
		arg.Kind,
		arg.Position,
		arg.ThumbKey,
		arg.MediumKey,
		arg.LargeKey,
		arg.AudioKey,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.Author,
		arg.License,
		arg.Source,
		arg.SourceUrl,
	)
	return err
}

const requeueStuckJobs = `-- name: RequeueStuckJobs :exec
UPDATE ingestion_job SET status = 'pending', updated_at = now()
WHERE status = 'running' AND updated_at < now() - interval '15 minutes'
`

// Se o worker morrer no meio de um job, ele fica "running" para sempre.
// Depois de 15 min sem atualização, devolvemos o job para a fila.
func (q *Queries) RequeueStuckJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, requeueStuckJobs)
	return err
}

const rescheduleStaleJobs = `-- name: RescheduleStaleJobs :exec
UPDATE ingestion_job SET status = 'pending', attempts = 0, next_run_at = now(), updated_at = now()
WHERE status = 'done' AND updated_at < now() - make_interval(secs => $1::double precision)
`

// Dados mudam (novas fotos, novos avistamentos): refaz jobs antigos.
func (q *Queries) RescheduleStaleJobs(ctx context.Context, refreshAfterSecs float64) error {
	_, err := q.db.Exec(ctx, rescheduleStaleJobs, refreshAfterSecs)
	return err
}
